version: "3"
services:
  token:
    build: .
    depends_on:
      - token_redis
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - "8081:8081"
  token_redis:
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"
